### ISSUE TITLE
Is this project complete

### ISSUE THREAD

**Issue by snandiga** [patrickhener/puffyCV#1]
Thanks for working on this project ... it really helped me to get started ... Is this project complete ? I am unable to detect the darts and am not sure what various configuration parameters really mean eg: ROI y, ROI Height, Surface-y, Center, FOV, Distance and Angle. Could you please post a picture and label sample values on it for clarity. Thanks for your help.

**Comment by patrickhener** [comment]
This project is still work in progress and not functioning at all right now. Next step will be to build the board setup and test it with two cameras. If this will work I'll have to adapt the Code to read 4 cameras as well. I am going to Update the README.md later on to reflect this.
